version: '3.5'

services:

  # cepher:
  #   build: .
  #   network_mode: host
  #   environment:
  #     - MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:16789
  #     - DEFAULT_IMAGE_SIZE=1
  #     - ENABLE_AUTO_CREATE_VOLUMES=true
  #     - LOG_LEVEL=debug
  #     - ETCD_URL=http://${HOST_IP}:12379
  #   privileged: true
  #   volumes:
  #     - /run/docker/plugins:/run/docker/plugins
  #     - /mnt:/mnt
  #     - /dev:/dev
  #     - /sys:/sys
  #     - /lib:/lib

  etcd0:
    image: quay.io/coreos/etcd
    network_mode: host
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:12379

  mon1:
    image: flaviostutz/ceph-monitor
    network_mode: host
    environment:
      - LOG_LEVEL=0
      - CREATE_CLUSTER=true
      - ETCD_URL=http://${HOST_IP}:12379
      - PEER_MONITOR_HOSTS=${HOST_IP}:26789,${HOST_IP}:36789
      - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:16789
      - MONITOR_BIND_PORT=16789

  mon2:
    image: flaviostutz/ceph-monitor
    network_mode: host
    environment:
      - ETCD_URL=http://${HOST_IP}:12379
      - PEER_MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:36789
      - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:26789
      - MONITOR_BIND_PORT=26789

  mon3:
    image: flaviostutz/ceph-monitor
    network_mode: host
    environment:
      - ETCD_URL=http://${HOST_IP}:12379
      - PEER_MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789
      - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:36789
      - MONITOR_BIND_PORT=36789

  mgr1:
    image: flaviostutz/ceph-manager
    ports:
      - 18443:8443 #dashboard https
      - 18003:8003 #restful https
      - 19283:9283 #prometheus
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379

  osd1:
    image: flaviostutz/ceph-osd
    network_mode: host
    pid: host
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:36789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - OSD_CRUSH_LOCATION=root=default host=host1
      - ETCD_URL=http://${HOST_IP}:12379
      # - OSD_PUBLIC_IP=${HOST_IP}
      # - OSD_CLUSTER_IP=${HOST_IP}

  osd2:
    image: flaviostutz/ceph-osd
    network_mode: host
    pid: host
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:36789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - OSD_CRUSH_LOCATION=root=default host=host2
      - ETCD_URL=http://${HOST_IP}:12379

  osd3:
    image: flaviostutz/ceph-osd
    network_mode: host
    pid: host
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=${HOST_IP}:16789,${HOST_IP}:26789,${HOST_IP}:36789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - OSD_CRUSH_LOCATION=root=default host=host3
      - ETCD_URL=http://${HOST_IP}:12379
